### ISSUE TITLE
🐛 [Bug report]: The npx create-react-play doesn't work on Mac

### ISSUE THREAD

**Issue by atapas** [reactplay/create-react-play#18]
**Describe the bug**
After submitting the create play form, the npx command doesn't work on the Mac terminal. It doesn't create the required scaffolding and boilerplate code. It works well on Windows.

**Comment by shyakadev** [comment]
I'm facing the same issue on ubuntu, can't create a play
![Screenshot from 2022-10-25 08-42-08](https://user-images.githubusercontent.com/16863527/197703084-5e8322ca-04f2-4a1f-8954-da4ed7653de4.png)
