### ISSUE TITLE
🐛 [Bug report]: weird syntax after creating a play in typescript

### ISSUE THREAD

**Issue by Angryman18** [reactplay/create-react-play#33]
### Descrcibe the bug?

found the below syntax after creating a typescript play and its throwing error on browser

### Steps to reproduce the bug?

creating a play in typescirpt will have the error

### Expected behavior

there should not be any error after creating a play in typescript

### Desktop (Please provide your system information)

Ubuntu version 22.04

### Screenshot / Screenshare

![Screenshot from 2023-01-29 20-33-19](https://user-images.githubusercontent.com/63530626/215335567-0e55212b-eddc-44b1-b59c-79d3fbb2f1ad.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by koustov** [comment]
> Assign it to someone I'm not able to fix it.

Actually @surya-situ , this issue is not with `react-play` repo. It belongs to [crate-react-play](https://github.com/reactplay/create-react-play) repo. You might want to give it another try

**Comment by surya-situ** [comment]
I have push the code can you check it out.
